SELECT P.INSTITUTION_CODE,
       P.INSTITUTION_SHORT_NAME,
       P.INST_CUS_NO,
       C.CUSTOMER_CODE,
       C.NAME               MUSTERI_ADI,
       P.PROFIT_CENTER_CODE KAR_MERKEZI,
       P.BLOCKED_DAY_COUNT AS BLOKE_GUN_SAYISI,
       SUM(PAYMENT_AMOUNT) AS ODEME_TUTARI
  FROM OFSA_DAILY.ORDER_PAYMENTS P,
       STAGE.EX_INFRA_CUST_CUST_CUST C
WHERE P.CUS_NO=C.CUSTOMER_CODE
   AND P.AS_OF_DATE = [?C90E317C42C34CBC06EDD6B3C03C7391[?    => Metis tarih promptu
GROUP BY
       P.INSTITUTION_CODE,
       P.INSTITUTION_SHORT_NAME,
       P.INST_CUS_NO,
       C.CUSTOMER_CODE,
       C.NAME,
       P.PROFIT_CENTER_CODE,
       P.BLOCKED_DAY_COUNT
UNION ALL
SELECT '12345'               AS INSTITUTION_CODE,
        'TEST'                AS INSTITUTION_SHORT_NAME,
        456                   AS INST_CUS_NO,
        '789456'              AS CUSTOMER_CODE,
        'TEST MUSTERISI'      AS  MUSTERI_ADI,
        'BİREYSEL'            AS  KAR_MERKEZI,
        5                     AS BLOKE_GUN_SAYISI,
        100                   AS ODEME_TUTARI
  FROM DUAL